preload = /home/hampus/.config/hypr/wallpapers/wall0.png
wallpaper = eDP-1,/home/hampus/.config/hypr/wallpapers/wall0.png

# disable splash text rendering over the wallpaper
splash = false

# ipc = off
